defaultAccount:
  income: Income:Unknown
  expenses: Expenses:Unknown
  base: Assets:Bank:Cathay
encoding: big5
rules:
  - pattern:
      - type: transaction
        query: /metadata/note
        value: 統一發票中獎
      - type: posting
        query: /account
        value: Income:Unknown
    transform:
      - type: posting
        query: /account
        value: Income:InvoiceLottery
  - pattern:
      - type: transaction
        query: /metadata/description
        vale: 信用卡款
      - type: posting
        query: /account
        value: Expenses:Unknown
    transform:
      - type: posting
        query: /account
        value: Liabilities:CreditCard:Cathay
  - pattern:
      - type: transaction
        query: /metadata/description
        vale: 花旗
      - type: posting
        query: /account
        value: Expenses:Unknown
    transform:
      - type: posting
        query: /account
        value: Liabilities:CreditCard:Citi
