defaultAccount:
  deposit: Income:Unknown
  withdraw: Expenses:Unknown
  base: Assets:Bank:Cathay
encoding: big5
defaultParsingFields: [說明]
rules:
  - pattern: (統一發票中獎)
    fields: [備註]
    type: deposit
    account: Liabilities:CreditCard:Cathay
  - pattern: (信用卡款)
    type: withdraw
    account: Liabilities:CreditCard:Cathay
  - pattern: (花旗)
    fields: [備註]
    type: withdraw
    account: Liabilities:CreditCard:Cathay
