defaultAccount:
  expenses: Expenses:Unknown
  income: Income:Unknown
  base: Liabilities:CreditCard:Cathay
encoding: big5
einvoiceIntegration: true
rules:
  - pattern:
      - type: transaction
        query: /narration
        value: ＫＯＫＯ一般回饋
      - type: directive
        query: /account
        value: Expenses:Unknown
    transform:
      - type: directive
        query: /account
        value: Income:CreditCard:Reward
