defaultAccount:
  deposit: Income:Unknown
  withdraw: Expenses:Unknown
  ethTx: Expenses:Ethereum:TransactionFee
connections:
  - type: ethereum
    address: "0x8b5e93256803c9d63a85d6b74e76eb8906919dd6"
    accountPrefix: Assets:Crypto:TestAccount
rules:
  - type: ethereum
    to: "0x6ab5bc70622763f270220127189f3e61237ae1f2"
    account: Assets:Crypto:DaiSaving
timestamp:
  ethereum: 0
