defaultAccount:
  income: Income:Unknown
  expenses: Expenses:Unknown
  ethTx: Expenses:Ethereum:TransactionFee
  pnl: Income:Crypto:PnL
connections:
  - type: ethereum
    address: "0x6344793A588C7B3076bf74562463998b2966eE91"
    accountPrefix: Assets:Crypto:TestAccount
rules:
  - pattern:
    - type: directive
      query: /symbol
      value: ETH-SYM
    transform:
    - type: directive
      query: /symbol
      value: SYM
  - pattern:
    - type: directive
      query: /metadata/address
      value: "0xd89c56dea56db24a51482e53909b0cfa8bba78aa"
    transform:
      - type: directive
        query: /account
        value: Assets:Crypto:DaiSaving
  - pattern:
      - type: transaction
        query: /metadata/to
        value: "0xd89c56dea56db24a51482e53909b0cfa8bba78aa"
      - type: directive
        query: /metadata/address
        value: "0x0000000000000000000000000000000000000000"
    transform:
      - type: directive
        query: /account
        value: Assets:Crypto:DaiSaving
excludeCoins:
  - KICK
timestamp:
  ethereum: "0"
coins:
  - symbol: BAT
    id: basic-attention-token
  - symbol: ETH
    id: ethereum
  - symbol: DAI
    id: dai
  - symbol: CDAI
    id: cdai
  - symbol: SAI
    id: sai
  - symbol: CSAI
    id: compound-sai
fiat: TWD
