defaultAccount:
  deposit: Income:Unknown
  withdraw: Expenses:Unknown
  ethTx: Expenses:Ethereum:TransactionFee
  pnl: Income:Crypto:PnL
connections:
  - type: ethereum
    address: "0x6344793A588C7B3076bf74562463998b2966eE91"
    accountPrefix: Assets:Crypto:TestAccount
rules:
  - type: ethereum
    pattern:
      address: "0xd89c56dea56db24a51482e53909b0cfa8bba78aa"
    transform:
      - field: account
        value: Assets:Crypto:DaiSaving
  - type: ethereum
    pattern:
      symbol: ETH-SYM
    transform:
      - field: symbol
        value: SYM
excludeCoins:
  - KICK
timestamp:
  ethereum: "0"
coins:
  - symbol: BAT
    id: basic-attention-token
  - symbol: ETH
    id: ethereum
  - symbol: DAI
    id: dai
  - symbol: CDAI
    id: cdai
  - symbol: SAI
    id: sai
  - symbol: CSAI
    id: compound-sai
fiat: TWD
